"""Pydantic model for the input of `turbo_lanczos.x` version `qe-5.2.1`.

This file has been generated automatically. Do not edit it manually.
"""

# ruff: noqa

from pathlib import Path
from pydantic import Field, field_validator
from typing import Annotated, Literal
from pydantic_espresso.models.template import EspressoInput, Namelist
from pydantic_espresso.utils import get_tmp_dir, get_pseudo_dir


class Lr_inputNamelist(Namelist):
    """Pydantic model for the `Lr_input` namelist."""

    title: str | None = Field(None, description="A string describing the job.")
    prefix: str = Field("pwscf", description="Sets the prefix for generated and read files. The files generated by the ground state pw.x run should have this same prefix.")
    outdir: Path = Field(./, description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.")
    wfcdir: Path = Field(./, description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.")
    restart: bool = Field(False, description="When set to .true., turbo_lanczos.x will attempt to restart from a previous interrupted calculation. (see restart_step variable).  Beware, if set to .false. turbo_lanczos.x will OVERWRITE any previous runs.")
    restart_step: int | None = Field(None, description="The code writes restart files every restart_step iterations. Restart files are automatically written at the end of itermax Lanczos steps.")
    lr_verbosity: int = Field(1, description="This integer variable controls the amount of information written to standard output.")
    disk_io: str = Field("default", description="Fine control of disk usage. Currently only 'reduced' is supported where no restart files are written, apart from the 'default' mode.")


class Lr_controlNamelist(Namelist):
    """Pydantic model for the `Lr_control` namelist."""

    itermax: int = Field(500, description="Number of Lanczos iterations to be performed.")
    ipol: int = Field(1, description="An integer variable that determines which element of the dynamical polarizability will be computed: 1 -> alpha_xx(omega), 2 -> alpha_yy(omega), and 3 -> alpha_zz(omega). When set to 4, three Lanczos chains are sequentially performed and the full polarizability tensor and the absorption coefficient are computed.")
    n_ipol: int | None = Field(None, description="Determines the number of zeta coefficients to be calculated for a given polarization direction.")
    ltammd: bool = Field(False, description="When set to .true. the Tamm-Dancoff approximation is used in constructing the Liouvillian.")
    no_hxc: bool = Field(False, description="When set to .true. the change in the internal field (Hartree and exchange-correlation) is ignored in the calculation, resulting in the independent electron approximation.")
    lrpa: bool = Field(False, description="When set to .true. the Random Phase Approximation is used (no exchange and correlation).")
    ecutfock: float | None = Field(None, description="Kinetic energy cutoff (Ry) for the exact exchange operator in EXX type calculations. By default this is the same as ecutrho but in some EXX calculations significant speed-up can be found by reducing ecutfock, at the expense of some loss in accuracy. Currently only implemented for the optimized gamma point only calculations.")
    charge_response: int = Field(0, description="When set to 1, the code computes the response of the charge density and writes it into a file format determined by the variable plot type. Setting charge response to 1 makes the presence of the card lr post mandatory.")
    pseudo_hermitian: bool = Field(True, description="When set to .true. the pseudo-Hermitian Lanczos algorithm is used. When set to .false. the non-Hermitian Lanczos biorthogonalization algorithm is used (which is two times slower).")
    d0psi_rs: bool = Field(False, description="When set to .true. the dipole is computed in the real space. When set to .false. the dipole is computed in the reciprocal space by computing [H,r]. Note, currently the commutator does not contain a contribution for hybrids [V_EXX,r]. See also the variable lshift_d0psi.")
    lshift_d0psi: bool = Field(True, description="This variable is used only when d0psi_rs=.true. a) If a molecule is placed in the corner of the supercell, there is a discontinuity problem for the position operator r, which is not periodic. By setting lshift_d0psi=.true. the discontinuity problem is solved by shifting the position operator r such that it is continuous and well defined. b) If a molecule is placed in the center of the supercell, there is no discontinuity problem for the position operator r, and thus you can set lshift_d0psi=.false. But if you still set it to .true., this will not harm, because the position operator will basically remain as it is, since it is always centered wrt the center of the molecule.")


class Lr_postNamelist(Namelist):
    """Pydantic model for the `Lr_post` namelist."""

    omeg: float = Field(0.0, description="The response of the charge density is calculated for this transition energy (in Rydberg units)")
    epsil: float = Field(0.0, description="The broadening/damping term (in Rydberg units).")
    beta_gamma_z_prefix: str = Field("pwscf", description="The prefix of the file where the beta gamma zeta coefficients from the first calculation can be set manually using this parameter. The file outdir/beta gamma z prefix.beta gamma z.x (where x=1-3) must exist.")
    w_T_npol: int = Field(1, description="Number of polarization directions considered in the previous calculation. It must be set to 3 if in the previous calculation ipol=4, it must be set to 1 otherwise.")
    plot_type: int = Field(1, description="An integer variable that determines the format of the file containing the charge density response. 1: A file containing the x y z grid coordinates and the corre- sponding value of the density is produced 2: The density response is written in Xcrysden format 3: The density response is written in the gaussian cube format.")


class TURBO_LANCZOSEspressoInput(EspressoInput):
    """Pydantic model for the input of `turbo_lanczos.x.`"""

    lr_input: Lr_inputNamelist = Field(default_factory=Lr_inputNamelist)
    lr_control: Lr_controlNamelist = Field(default_factory=Lr_controlNamelist)
    lr_post: Lr_postNamelist = Field(default_factory=Lr_postNamelist)
