"""Functions for converting the content of XML files to Pydantic models as raw strings.

We generate static python code (cf. dynamic model creation) because we want to be able to
inspect the models statically.
"""

from pathlib import Path
import warnings
from typing import Tuple, Any
from xml.etree.ElementTree import Element, ParseError
from defusedxml.ElementTree import parse
from pydantic_espresso.models.inputs import import_parameter_models
from pydantic_espresso.xml_files import directory as xml_directory

type_mapping = {"INTEGER": int, "REAL": float, "LOGICAL": bool, "CHARACTER": str, "STRING": str,
                "integer": int, "real": float, "logical": bool, "character": str, "string": str,
                "DOUBLE": float, "CHARATER": str}


class InvalidXMLStructureError(Exception):
    """Raised when the structure of the XML file is not as expected."""


def sanitize_xml(xml_path: Path) -> Path:

    with open(xml_path) as f:
        xmlstr = f.read()

    for tag in ["b", "ref", "link"]:
        xmlstr = xmlstr.replace(f"<{tag}>", "").replace(f"</{tag}>", "")

    for tag in ["br"]:
        xmlstr = xmlstr.replace(f"<{tag}/>", "")

    # Replace all links <a href="url">text</a> with text (url)
    while '<a href="' in xmlstr:
        start = xmlstr.find('<a href="')
        end = xmlstr.find('">', start)
        url = xmlstr[start + 9 : end]
        text_end = xmlstr.find("</a>", end)
        text = xmlstr[end + 2 : text_end]
        xmlstr = xmlstr[:start] + f"{text} ({url})" + xmlstr[text_end + 4 :]
    
    sanitized_path = xml_path.with_stem(xml_path.stem + "_sanitized")
    with open(sanitized_path, "w") as f:
        f.write(xmlstr)

    return sanitized_path


def convert_all_xml_files_to_models():
    for xml_path in xml_directory.rglob("*.xml"):
        print(f"Processing {xml_path}...", end=" ")
        try:
            model_str = convert_xml_file_to_model(xml_path, version=xml_path.parent.name)
        except ParseError as e:
            print(f"failed: {e}")
            continue
        except InvalidXMLStructureError as e:
            print(f"failed: {e}")
            continue

        model_file = str(xml_path).replace(".", "_").replace("-", "_").replace("_xml", ".py").replace("xml_files", "models").replace("INPUT_", "").lower()
        model_dir = Path(model_file).parent
        if not model_dir.exists():
            model_dir.mkdir(parents=True, exist_ok=True)
            # Create an empty __init__.py file
            with open(model_dir / "__init__.py", "w") as f:
                f.write('"""Pydantic models for Quantum ESPRESSO executables.\n\nThis file is automatically generated; do not edit.\n"""' )
        with open(model_file, "w") as f:
            f.write(model_str)
        print(f"succeeded")


def convert_xml_file_to_model(xml_file: Path, version: str = "latest") -> str:
    """Convert an XML file to raw python code that defines the corresponding Pydantic model."""

    # Sanitize the XML file
    sanitized_xml = sanitize_xml(xml_file)

    try:
        tree = parse(sanitized_xml)
    finally:
        # Remove the sanitized XML file
        sanitized_xml.unlink(missing_ok=True)

    root = tree.getroot()
    return convert_xml_tree_to_model(root, version=version)


def convert_xml_tree_to_model(root: Element, version: str = "latest") -> str:
    """Convert an XML tree to raw python code that defines the corresponding Pydantic model."""
    field_definitions = {}
    mappings = {}
    for namelist in root.findall("namelist"):
        namelist_name = namelist.attrib["name"].capitalize()
        field_definitions[namelist_name] = {}
        mappings[namelist_name] = {}
        for var in namelist.findall("var"):

            name = var.attrib["name"]
            if name == "lambda":
                # Avoid nameclash with the lambda function in Python
                name = "Lambda"

            field_definition, mapping = _parse_var(var)

            if field_definition is None:
                continue

            field_definitions[namelist_name][name] = field_definition

            if mapping:
                mappings[namelist_name][name] = mapping

    # class_definitions.update(**fields_to_patch)

    return _generate_model_string(root.attrib['program'], field_definitions, mappings, version=version)


def _parse_var(var: Element) -> Tuple[str | None, dict[str, dict[Any, Any]]]:
    name = var.attrib["name"]

    xml_type_str = var.attrib.get("type", None)
    if xml_type_str is None:
        raise InvalidXMLStructureError(f"`{name}` is missing the `type` field.")
    python_type = type_mapping[xml_type_str]
    # Manual patching of directories
    if name in ["pseudo_dir", "outdir", "wfcdir"]:
        python_type = Path

    description_element = var.find("info")
    options = None if python_type is float else var.find("options")  # Pydantic does not support float literals
    default = var.find("default")

    description = "" if description_element is None or description_element.text is None else description_element.text
    if options is not None:
        for info in options.findall("info"):
            assert info.text is not None
            description += info.text

    # Sanitize the description
    description = " ".join([line.strip() for line in description.strip(" \n'" + '"').replace('"', "'").split("\n")])

    if description in ["OBSOLETE - NO LONGER IMPLEMENTED"]:
        return None, {}

    type_str, mapping = _get_type_str(name, python_type, options)

    default_str = _get_default_str(name, python_type, default)

    if default_str == "None":
        if options is None:
            type_str += " | None"
        elif "None" not in type_str:
            # If there are options, we need to add the None type to the options
            type_str = type_str.replace("Literal[", "Literal[None, ")

    return f'{type_str} = Field({default_str}, description="{description}")', mapping


def _get_type_str(name: str, python_type: type, options: Element | None) -> Tuple[str, dict]:
    """Determine the string to add for the type of the field."""
    # if name in types_to_patch:
    #     return types_to_patch[name]

    if options:
        type_str, mapping = _get_options_str_and_mapping(options, python_type)
    elif name == "ibrav":
        type_str = "Literal[0, 1, 2, 3, -3, 4, 5, -5, 6, 7, 8, 9, -9, 91, 10, 11, 12, -12, 13, -13, 14]"
        mapping = {}
    else:
        type_str = python_type.__name__
        mapping = {}

    return type_str, mapping


def _get_options_str_and_mapping(options: Element, python_type: type) -> Tuple[str, dict[Any, Any]]:
    options_list = []
    mapping = {}
    for opt in options.findall("opt"):
        val = opt.attrib["val"]

        # Manual patches
        if val.startswith("dftd3_version = "):
            val = val.replace("dftd3_version = ", "")
        
        if "," in val:
            val_strs = [_get_value_str(v, python_type) for v in val.split(",")]
            val_str = val_strs[0]
            mapping.update({v.strip('"'): val_str.strip('"') for v in val_strs})
        else:
            val_str = _get_value_str(val.split(",")[0], python_type)

        options_list.append(val_str)

    return "Literal[" + ", ".join(options_list) + "]", mapping


def _get_value_str(text: str, python_type) -> str:
    sanitized_text = text.strip(" '\n" + '"').replace("\n", " ")
    if sanitized_text == "value of the $ESPRESSO_PSEUDO environment variable if set; '$HOME/espresso/pseudo/' otherwise":
        # Manual patch of pseudo_dir
        default_str = "default_factory=get_pseudo_dir"
    elif sanitized_text == "value of the ESPRESSO_TMPDIR environment variable if set; current directory ('./') otherwise":
        # Manual patch of tmp_dir
        default_str = "default_factory=get_tmp_dir"
    elif sanitized_text == "same as outdir":
        default_str = "default_factory=get_tmp_dir"
    elif sanitized_text.lower().strip(".") == "false":
        default_str = "False"
    elif sanitized_text.lower().strip(".") == "true":
        default_str = "True"
    elif python_type is str:
        default_str = '"' + sanitized_text + '"' 
        if " " in default_str:
            # In this case the default text is probably a sentence rather than a value describing conditional logic
            # which we should not use as a default value
            default_str = "None"
    else:
        try:
            python_type(sanitized_text)
            default_str = sanitized_text
        except:
            warnings.warn(f"Failed to parse {text}; defaulting to None.", stacklevel=2)
            default_str = "None"
    return default_str


def _get_default_str(
    name: str, python_type: type, default: Element | None) -> str:

    if default is not None:
        if default.text is None:
            raise InvalidXMLStructureError(f"Missing text in XML file for `{name}`.")
        default_str = _get_value_str(default.text, python_type)
    elif name == "ibrav":
        # Manually patching ibrav
        default_str = "0"
    else:
        # We could do "..." here, but we want to reduce the number of required fields
        default_str = "None"
    return default_str


def _generate_mapping_validator(name: str, mapping: dict[str, str]) -> str:
    """Generate a field validator that converts the value following the mapping."""
    mapping_str = "{" + ", ".join([f'"{k}": "{v}"' for k, v in mapping.items()]) + "}"
    return f"""
    @field_validator("{name}", mode="before")
    def map_{name}(cls, v):
        mapping = {mapping_str}
        return mapping.get(v, v)"""


def _generate_namelist_string(name: str, fields: dict[str, str], mappings: dict[str, dict[str, str]]) -> str:
    """Convert a dictionary of fields into a Namelist class definition."""
    return (f"class {name}Namelist(Namelist):\n    "
        + '"""'
        + f"Pydantic model for the `{name}` namelist."
        + '"""\n'
        + "\n".join([_generate_mapping_validator(k, v) for k, v in mappings.items()]) + "\n"
        + "\n".join([f"    {k}: {v}" for k, v in fields.items()])
    )

def _generate_model_string(executable: str, class_definitions: dict[str, dict[str, str]], mappings: dict[str, dict[str, dict[str, str]]], version: str) -> str:
    """Convert a dictionary of class definitions to raw python code defining a Pydantic model."""
    return (
        '"""'
        + f"""Pydantic model for the input of `{executable.lower()}` version `{version}`.

This file has been generated automatically. Do not edit it manually.
"""
        + '"""'
        + f"""

# ruff: noqa

from pathlib import Path
from pydantic import Field, field_validator
from typing import Annotated, Literal
from pydantic_espresso.models.template import EspressoInput, Namelist
from pydantic_espresso.utils import get_tmp_dir, get_pseudo_dir
{import_parameter_models}

""" + """


""".join(_generate_namelist_string(name, fields, mappings[name]) for name, fields in class_definitions.items()) + f"""


class {executable.upper().replace('.X', '')}EspressoInput(EspressoInput):
    """
        + '"""'
        + f"Pydantic model for the input of `{executable}.`"
        + '"""'
        + """

"""
        + "\n".join([f"    {k.lower()}: {k}Namelist = Field(default_factory={k}Namelist)" for k in class_definitions.keys()])
        + "\n"
    )
