"""Pydantic model for the input of `turbo_magnons.x` version `qe-6.8`.

This file has been generated automatically. Do not edit it manually.
"""

# ruff: noqa

from pathlib import Path
from pydantic import Field, field_validator
from typing import Literal
from pydantic_espresso.models.template import EspressoInput, Namelist
from pydantic_espresso.utils import get_tmp_dir, get_pseudo_dir


class Lr_inputNamelist(Namelist):
    """Pydantic model for the `Lr_input` namelist."""

    prefix: str = Field(
        "pwscf",
        description="Sets the prefix for generated and read files. The files generated by the ground state pw.x run must have this same prefix.",
    )
    outdir: Path = Field(
        Path("./"),
        description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.",
    )
    restart: bool = Field(
        False,
        description="When set to .true., turbo_magnons.x will attempt to restart from a previous interrupted calculation. (see restart_step variable). Beware, if set to .false. turbo_magnons.x will OVERWRITE any previous runs.",
    )
    restart_step: int | None = Field(
        None,
        description="The code writes restart files every restart_step iterations. Restart files are automatically written at the end of itermax Lanczos steps.",
    )
    lr_verbosity: int = Field(
        1,
        description="This integer variable controls the amount of information written to standard output.",
    )
    disk_io: str = Field(
        "default",
        description="Fine control of disk usage. Currently only 'reduced' is supported where no restart files are written, apart from the 'default' mode.",
    )


class Lr_controlNamelist(Namelist):
    """Pydantic model for the `Lr_control` namelist."""

    itermax: int = Field(500, description="Number of Lanczos iterations to be performed.")
    pseudo_hermitian: bool = Field(
        True,
        description="When set to .true. the pseudo-Hermitian Lanczos algorithm is used. When set to .false. the non-Hermitian Lanczos biorthogonalization algorithm is used (which is two times slower).",
    )
    approximation: str = Field(
        "TDDFT",
        description="A string describing a level of theory: 'TDDFT'            - Time-Dependent Local Density Approximation or Time-Dependent Generalized Gradient Approximation (depending on the XC functional), 'IPA'              - Independent Particle Approximation,",
    )
    ipol: int = Field(
        1,
        description="An integer variable that determines which element of the dynamical magnetic susceptibility will be computed: 1 -> chi_xx(omega), 2 -> chi_yy(omega), and 3 -> chi_zz(omega). When set to 4, three Lanczos chains are sequentially performed and the full susceptibility tensor is computed.",
    )


class TURBOMAGNONSEspressoInput(EspressoInput):
    """Pydantic model for the input of `turbo_magnons.x.`"""

    lr_input: Lr_inputNamelist = Field(default_factory=lambda: Lr_inputNamelist())
    lr_control: Lr_controlNamelist = Field(default_factory=lambda: Lr_controlNamelist())
