"""Pydantic model for the input of `turbo_eels.x` version `qe-5.2.0`.

This file has been generated automatically. Do not edit it manually.
"""

# ruff: noqa

from pathlib import Path
from pydantic import Field, field_validator
from typing import Annotated, Literal
from pydantic_espresso.models.template import EspressoInput
from pydantic_espresso.namelist import Namelist
from pydantic_espresso.utils import get_tmp_dir, get_pseudo_dir


class LrInputNamelist(Namelist):
    """Pydantic model for the `lr_input` namelist."""

    prefix: str = Field(
        "pwscf",
        description="Sets the prefix for generated and read files. The files generated by the ground state pw.x run must have this same prefix.",
    )
    outdir: Path = Field(
        Path("./"),
        description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.",
    )
    restart: bool = Field(
        False,
        description="When set to .true., turbo_eels.x will attempt to restart from a previous interrupted calculation. (see restart_step variable). Beware, if set to .false. turbo_eels.x will OVERWRITE any previous runs.",
    )
    restart_step: int | None = Field(
        None,
        description="The code writes restart files every restart_step iterations. Restart files are automatically written at the end of itermax Lanczos steps.",
    )
    lr_verbosity: int = Field(
        1,
        description="This integer variable controls the amount of information written to standard output.",
    )
    disk_io: str = Field(
        "default",
        description="Fine control of disk usage. Currently only 'reduced' is supported where no restart files are written, apart from the 'default' mode.",
    )


class LrControlNamelist(Namelist):
    """Pydantic model for the `lr_control` namelist."""

    itermax: int = Field(500, description="Number of Lanczos iterations to be performed.")
    pseudo_hermitian: bool = Field(
        True,
        description="When set to .true. the pseudo-Hermitian Lanczos algorithm is used. When set to .false. the non-Hermitian Lanczos biorthogonalization algorithm is used (which is two times slower).",
    )
    approximation: str = Field(
        "TDDFT",
        description="A string describing a level of theory: 'TDDFT'            - Time-Dependent Local Density Approximation or Time-Dependent Generalized Gradient Approximation (depending on the XC functional), 'IPA'              - Independent Particle Approximation, 'RPA_with_CLFE'    - Random Phase Approximation with Crystal Local Field Effects.",
    )
    qi: int | None = Field(
        None,
        description="The values of the transferred momentum in Cartesian coordinates (i=1,2,3) in units of 2pi/a0 (a0 = lattice parameter). It must be specified as q1, q2, q3.",
    )


class TURBOEELSEspressoInput(EspressoInput):
    """Pydantic model for the input of `turbo_eels.x`"""

    lr_input: LrInputNamelist = Field(default_factory=lambda: LrInputNamelist())
    lr_control: LrControlNamelist = Field(default_factory=lambda: LrControlNamelist())
