"""Pydantic model for the input of `turbo_eels.x` version `qe-7.3.1`.

This file has been generated automatically. Do not edit it manually.
"""

# ruff: noqa

from pathlib import Path
from pydantic import Field, field_validator
from typing import Annotated, Literal
from pydantic_espresso.models.template import EspressoInput, Namelist
from pydantic_espresso.utils import get_tmp_dir, get_pseudo_dir


class Lr_inputNamelist(Namelist):
    """Pydantic model for the `Lr_input` namelist."""

    prefix: str = Field("pwscf", description="Sets the prefix for generated and read files. The files generated by the ground state pw.x run must have this same prefix.")
    outdir: Path = Field(./, description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.")
    restart: bool = Field(False, description="When set to .true., turbo_eels.x will attempt to restart from a previous interrupted calculation. (see restart_step variable). Beware, if set to .false. turbo_eels.x will OVERWRITE any previous runs.")
    restart_step: int | None = Field(None, description="The code writes restart files every restart_step iterations. Restart files are automatically written at the end of itermax Lanczos steps.")
    lr_verbosity: int = Field(1, description="This integer variable controls the amount of information written to standard output.")
    disk_io: str = Field("default", description="Fine control of disk usage. Currently only 'reduced' is supported where no restart files are written, apart from the 'default' mode.")


class Lr_controlNamelist(Namelist):
    """Pydantic model for the `Lr_control` namelist."""

    approximation: Literal["TDDFT", "IPA", "RPA_with_CLFE"] = Field("TDDFT", description="A string describing a level of theory:")
    calculator: Literal["lanczos", "sternheimer"] = Field("lanczos", description="Variable that controls which algorithm is used to compute EELS spectra.")
    itermax: int = Field(500, description="When calculator = 'lanczos', itermax is the maximum number of Lanczos iterations that will be performed. When calculator = 'sternheimer', itermax is the maximum number of iterations in a SCF step for each frequency.")
    pseudo_hermitian: bool = Field(True, description="This variable is used only when calculator = 'lanczos'. When set to .true. the pseudo-Hermitian Lanczos algorithm is used. When set to .false. the non-Hermitian Lanczos biorthogonalization algorithm is used (which is two times slower).")
    alpha_mix(i): float | None = Field(None, description="This variable is used only when calculator = 'sternheimer'. Mixing parameter (for the i-th iteration) for updating the response SCF potential using the modified Broyden method: D.D. Johnson, PRB 38, 12807 (1988) (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.38.12807).")
    epsil: float = Field(0.02, description="This variable is used only when calculator = 'sternheimer'. The broadening/damping term (in Rydberg units).")
    units: int = Field(0, description="This variable is used only when calculator = 'sternheimer'. The unit system used for the output, for start, end, and increment input parameters. 0 = Rydbergs, 1 = Electron volts.")
    start: float = Field(0.0, description="This variable is used only when calculator = 'sternheimer'. start is the value of frequency starting from which the susceptibility and the loss function (-Im(1/eps)) will be computed. start is specified in units controlled by units.")
    end: float = Field(2.5, description="This variable is used only when calculator = 'sternheimer'. end is the value of frequency up to which the susceptibility and the loss function (-Im(1/eps)) will be computed. end is specified in units controlled by units.")
    increment: float = Field(0.001, description="This variable is used only when calculator = 'sternheimer'. increment is an incremental step used to define the mesh of frequencies between start and end. increment is specified in units controlled by units.")
    ethr_nscf: float | None = Field(None, description="Threshold for the convergence of eigenvalues during the iterative diagonalization of the Hamiltonian in the non-self-consistent-field (NSCF) calculation at k and k+q points. Note, this quantity is NOT extensive.")


class TURBO_EELSEspressoInput(EspressoInput):
    """Pydantic model for the input of `turbo_eels.x.`"""

    lr_input: Lr_inputNamelist = Field(default_factory=Lr_inputNamelist)
    lr_control: Lr_controlNamelist = Field(default_factory=Lr_controlNamelist)
