"""Pydantic model for the input of `turbo_magnon.x` version `develop`.

This file has been generated automatically. Do not edit it manually.
"""

from pathlib import Path
from textwrap import dedent
from typing import Annotated, Literal

from pydantic import Field

from pydantic_espresso.base import EspressoInput
from pydantic_espresso.namelist import Namelist
from pydantic_espresso.quantity import Quantity


class LrInputNamelist(Namelist):
    """Pydantic model for the `LR_INPUT` namelist."""

    prefix: str = Field(
        "pwscf",
        description=dedent(
            """\
            Sets the prefix for generated and read files. The files generated by the ground state
            pw.x run must have this same prefix."""
        ),
    )
    outdir: Path | None = Field(
        None,
        json_schema_extra={
            "conditional_default": [
                {"when": "ESPRESSO_TMPDIR is set", "value": "from_environment"},
                {"when": None, "value": "./"},
            ],
        },
        description=dedent(
            """\
            The directory that contains the run critical files, which include the files generated
            by ground state pw.x run."""
        ),
    )
    restart: bool = Field(
        False,
        description=dedent(
            """\
            When set to .true., turbo_magnons.x will attempt to restart from a previous interrupted
            calculation. (see restart_step variable). Beware, if set to .false. turbo_magnons.x
            will OVERWRITE any previous runs."""
        ),
    )
    restart_step: int | None = Field(
        None,
        json_schema_extra={"default_expr": "itermax + 1"},
        description=dedent(
            """\
            The code writes restart files every restart_step iterations. Restart files are
            automatically written at the end of itermax Lanczos steps."""
        ),
    )
    lr_verbosity: int = Field(
        1,
        description=dedent(
            """\
            This integer variable controls the amount of information written to standard output."""
        ),
    )
    disk_io: Literal["default", "reduced"] = Field(
        "default",
        description=dedent(
            """\
            Fine control of disk usage.
            - 'default': Standard disk I/O: restart files are written so the calculation can be
              resumed.
            - 'reduced': Reduced disk I/O: no restart files are written."""
        ),
    )


class LrControlNamelist(Namelist):
    """Pydantic model for the `LR_CONTROL` namelist."""

    itermax: int = Field(500, description="Number of Lanczos iterations to be performed.")
    pseudo_hermitian: bool = Field(
        True,
        description=dedent(
            """\
            When set to .true. the pseudo-Hermitian Lanczos algorithm is used. When set to .false.
            the non-Hermitian Lanczos biorthogonalization algorithm is used (which is two times
            slower)."""
        ),
    )
    approximation: Literal["TDDFT", "IPA"] = Field(
        "TDDFT",
        description=dedent(
            """\
            A string describing a level of theory:
            - 'TDDFT': Time-Dependent Local Density Approximation or Time-Dependent Generalized
              Gradient Approximation (depending on the XC functional).
            - 'IPA': Independent Particle Approximation."""
        ),
    )
    ipol: int = Field(
        1,
        description=dedent(
            """\
            An integer variable that determines which column of the dynamical magnetic
            susceptibility will be computed: 1 -> chi_ax(omega), 2 -> chi_ay(omega), and 3 ->
            chi_az(omega), with a=(x,y,z). When set to 4, three Lanczos chains are sequentially
            performed and the full susceptibility tensor is computed."""
        ),
    )
    q1: Annotated[float, Quantity(units="tpiba", dimensionality="length^-1")] = Field(
        1.0,
        description=dedent(
            """\
            The values of the transferred momentum q = (q1, q2, q3) in Cartesian coordinates in
            units of 2pi/a, where 'a' is the lattice parameter."""
        ),
    )
    q2: Annotated[float, Quantity(units="tpiba", dimensionality="length^-1")] = Field(
        1.0,
        description=dedent(
            """\
            The values of the transferred momentum q = (q1, q2, q3) in Cartesian coordinates in
            units of 2pi/a, where 'a' is the lattice parameter."""
        ),
    )
    q3: Annotated[float, Quantity(units="tpiba", dimensionality="length^-1")] = Field(
        1.0,
        description=dedent(
            """\
            The values of the transferred momentum q = (q1, q2, q3) in Cartesian coordinates in
            units of 2pi/a, where 'a' is the lattice parameter."""
        ),
    )


class TURBOMAGNONInput(EspressoInput):
    """Pydantic model for the input of `turbo_magnon.x`."""

    lr_input: LrInputNamelist = Field(default_factory=lambda: LrInputNamelist())
    lr_control: LrControlNamelist = Field(default_factory=lambda: LrControlNamelist())
