"""Pydantic model for the input of `turbo_magnon.x` version `develop`.

This file has been generated automatically. Do not edit it manually.
"""

from pathlib import Path
from typing import Literal

from pydantic import Field

from pydantic_espresso.models.template import EspressoInput
from pydantic_espresso.namelist import Namelist


class LrInputNamelist(Namelist):
    """Pydantic model for the `LR_INPUT` namelist."""

    prefix: str = Field(
        "pwscf",
        description=(
            "Sets the prefix for generated and read files. The files generated by the ground state "
            "pw.x run must have this same prefix."
        ),
    )
    outdir: Path | None = Field(
        None,
        json_schema_extra={
            "conditional_default": [
                {
                    "when": "environment variable ESPRESSO_TMPDIR is set and non-blank",
                    "value": "value of the ESPRESSO_TMPDIR environment variable",
                },
                {"when": None, "value": "'./'"},
            ],
        },
        description=(
            "The directory that contains the run critical files, which include the files generated "
            "by ground state pw.x run."
        ),
    )
    restart: bool = Field(
        False,
        description=(
            "When set to .true., turbo_magnons.x will attempt to restart from a previous "
            "interrupted calculation. (see restart_step variable). Beware, if set to .false. "
            "turbo_magnons.x will OVERWRITE any previous runs."
        ),
    )
    restart_step: int | None = Field(
        None,
        json_schema_extra={"default_expr": "itermax + 1"},
        description=(
            "The code writes restart files every restart_step iterations. Restart files are "
            "automatically written at the end of itermax Lanczos steps."
        ),
    )
    lr_verbosity: int = Field(
        1,
        description=(
            "This integer variable controls the amount of information written to standard output."
        ),
    )
    disk_io: Literal["default", "reduced"] = Field(
        "default", description="Fine control of disk usage."
    )


class LrControlNamelist(Namelist):
    """Pydantic model for the `LR_CONTROL` namelist."""

    itermax: int = Field(500, description="Number of Lanczos iterations to be performed.")
    pseudo_hermitian: bool = Field(
        True,
        description=(
            "When set to .true. the pseudo-Hermitian Lanczos algorithm is used. When set to "
            ".false. the non-Hermitian Lanczos biorthogonalization algorithm is used (which is two "
            "times slower)."
        ),
    )
    approximation: Literal["TDDFT", "IPA"] = Field(
        "TDDFT", description="A string describing a level of theory:"
    )
    ipol: int = Field(
        1,
        description=(
            "An integer variable that determines which column of the dynamical magnetic "
            "susceptibility will be computed: 1 -> chi_ax(omega), 2 -> chi_ay(omega), and 3 -> "
            "chi_az(omega), with a=(x,y,z). When set to 4, three Lanczos chains are sequentially "
            "performed and the full susceptibility tensor is computed."
        ),
    )


class TURBOMAGNONEspressoInput(EspressoInput):
    """Pydantic model for the input of `turbo_magnon.x`."""

    lr_input: LrInputNamelist = Field(default_factory=lambda: LrInputNamelist())
    lr_control: LrControlNamelist = Field(default_factory=lambda: LrControlNamelist())
