"""Pydantic model for the input of `turbo_spectrum.x` version `develop`.

This file has been generated automatically. Do not edit it manually.
"""

from pathlib import Path
from typing import Annotated, Literal

from pydantic import Field, field_validator

from pydantic_espresso.models.template import EspressoInput
from pydantic_espresso.namelist import Namelist
from pydantic_espresso.quantity import Quantity


class LrInputNamelist(Namelist):
    """Pydantic model for the `LR_INPUT` namelist."""

    @field_validator("td", mode="before")
    @classmethod
    def map_td(cls, v: str) -> str:
        """Map equivalent values for `td` onto a canonical value."""
        mapping = {"david": "davidson"}
        return mapping.get(v, v)

    prefix: str = Field(
        "pwscf",
        description=(
            "Sets the prefix for generated and read files. The files generated by the ground state "
            "pw.x run should have this same prefix."
        ),
    )
    outdir: Path | None = Field(
        None,
        json_schema_extra={
            "conditional_default": [
                {
                    "when": "ESPRESSO_TMPDIR environment variable is set and non-blank",
                    "value": "value of the ESPRESSO_TMPDIR environment variable",
                },
                {"when": None, "value": "'./'"},
            ],
        },
        description=(
            "The directory that contains the run critical files, which include the files generated "
            "by ground state pw.x run."
        ),
    )
    verbosity: int = Field(
        0,
        description=(
            "This integer variable controls the amount of information written to standard output."
        ),
    )
    itermax0: int = Field(
        1000, description="Number of Lanczos coefficients to be read from the file."
    )
    itermax: int = Field(
        1000,
        description=(
            "The total number of Lanczos coefficients that will be considered in the calculation "
            "of the polarizability/absorption coefficient. If itermax > itermax0, the Lanczos "
            "coefficients in between itermax0+1 and itermax will be extrapolated."
        ),
    )
    extrapolation: Literal["osc", "constant", "no"] = Field(
        "no", description="Sets the extrapolation scheme."
    )
    epsil: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.02,
        description=(
            "The broadening/damping term. In Rydberg units if magnons=.false., in meV if magnons = "
            ".true."
        ),
    )
    units: int = Field(
        0,
        description=(
            "The unit system used for the output and the start, end and increment input "
            "parameters. (only meV used in that case).  0 = Rydbergs, 1 = Electron volts, 2 = "
            "Nanometres per electron volts, 3 = milli Electron volts (only for magnons=.true.)"
        ),
    )
    start: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.0,
        description=(
            "The polarizability and the absorption coefficient are computed starting from this "
            "value. In units set."
        ),
    )
    end: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        2.5,
        description=(
            "The polarizability and the absorption coefficient are computed up to this value. In "
            "units set."
        ),
    )
    increment: Annotated[float, Quantity(units="Ry", dimensionality="energy")] = Field(
        0.001,
        description="Incremental step used to define the mesh between start and end. In units set.",
    )
    ipol: int = Field(
        1,
        description=(
            "An integer variable that determines which element of the dynamical polarizability "
            "will be computed: 1 -> alpha_xx(omega), 2 -> alpha_yy(omega), and 3 -> "
            "alpha_zz(omega). When set to 4, three Lanczos chains are sequentially performed and "
            "the full polarizability tensor and the absorption coefficient are computed."
        ),
    )
    eels: bool = Field(
        False,
        description="Must be set to .true. for EELS. EELS-specific operations will be performed.",
    )
    magnons: bool = Field(
        False, description="Must be set to .true. for magnon-calculation post-processing."
    )
    td: Literal["lanczos", "davidson"] = Field(
        "lanczos",
        description="Specifies which algorithm's output is post-processed to compute the spectrum.",
    )
    eign_file: str = Field(
        "pwscf.eigen",
        description=(
            "The name of the file produced by the turbo_davidson.x code, in which are written the "
            "eigenvalues."
        ),
    )


class TURBOSPECTRUMEspressoInput(EspressoInput):
    """Pydantic model for the input of `turbo_spectrum.x`."""

    lr_input: LrInputNamelist = Field(default_factory=lambda: LrInputNamelist())
