"""Pydantic model for the input of `turbo_davidson.x` version `qe-6.4.1`.

This file has been generated automatically. Do not edit it manually.
"""

# ruff: noqa

from pathlib import Path
from pydantic import Field, field_validator
from typing import Literal
from pydantic_espresso.models.template import EspressoInput, Namelist
from pydantic_espresso.utils import get_tmp_dir, get_pseudo_dir


class Lr_inputNamelist(Namelist):
    """Pydantic model for the `Lr_input` namelist."""


    prefix: str = Field("pwscf", description="Sets the prefix for generated and read files. The files generated by the ground state pw.x run should have this same prefix.")
    outdir: Path = Field(Path("./"), description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.")
    wfcdir: Path = Field(Path("./"), description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.")
    max_seconds: float | None = Field(None, description="jobs stops after 'max_seconds' CPU time. Use this option in conjunction with option 'restart' if you need to split a job too long to complete into shorter jobs that fit into your batch queues.")
    restart: bool = Field(False, description="When set to .true., turbo_davidson.x will attempt to restart from a previous interrupted calculation if 'max_seconds' was specified. Beware, if set to .false. turbo_davidson.x will OVERWRITE any previous runs.")
    lr_verbosity: int = Field(1, description="This integer variable controls the amount of information written to standard output.")
    disk_io: str = Field("default", description="Fine control of disk usage. Currently only 'reduced' is supported where no restart files are written, apart from the 'default' mode.")


class Lr_davNamelist(Namelist):
    """Pydantic model for the `Lr_dav` namelist."""


    num_eign: int = Field(1, description="Number of eigenstates to be calculated.")
    num_init: int = Field(2, description="Number of trial vectors. Usually it is twice as large as the number of eigenstates to be calculated (see 'num_eign').")
    if_random_init: bool = Field(False, description="When set to .true. trial vectors are chosen randomly, otherwise they are guessed from the ground-state calculation. If p_nbnd_occ * p_nbnd_virt < num_init, this term is forced to be .true. The usage of random trial vectors should cause only a slower convergence, and do not affect the final results.")
    num_basis_max: int = Field(20, description="Maximum number of basis vectors allowed in the subspace. When this number is reached, a discharging routine is called. The memory requirement of the Davidson algorithm is mainly determined by this variable (an estimation of the memory is reported at the beginning of the run).")
    residue_conv_thr: float = Field(1.0E-4, description="Threshold for the convergence. When the square of the residue is smaller than this value, the convergence is achieved.")
    precondition: bool = Field(True, description="If set to .true. a precondition is used. At this moment, one sees no reason why not to use the precondition.")
    single_pole: bool = Field(False, description="A slightly better way to set the initial trial vectors, but the improvement is really small. Currently this flag can be used only with LDA/PBE + NC PPs. So do not use it unless it is really necessary.")
    if_dft_spectrum: bool = Field(False, description="When set to .true. the independent particle approximation is used, i.e. the Hartree and exchange-correlation response contributions are neglected.")
    reference: float = Field(0.0e0, description="Reference energy in units of Ry. This variable is used to constrain the Davidson algorithm to converge the eigenstates having the energy closest to the reference energy. In this way one can calculate less eigenstates at once, and to perform multiple calculations with different reference energies (the post-processing code tddfpt_calculate_spectrum.x can be used for this purpose).")
    broadening: float = Field(0.005e0, description="Lorentzian broadening (Ry) to broaden the absorption spectrum.")
    start: float = Field(0.0e0, description="The lower limit of the energy (Ry) scale for the spectrum calculation.")
    finish: float = Field(1.0e0, description="The upper limit of the energy (Ry) scale for the spectrum calculation.")
    step: float = Field(0.001e0, description="Energy step (Ry) for the spectrum calculation.")
    p_nbnd_occ: int = Field(10, description="Number of occupied states selected from the total number of occupied states computed by PWscf. This variable is useful if there are too many occupied states but your are interested in only some of them. In priciple this variable and 'p_nbnd_virt' affect only the interpretation of the eigenstates, but do not effect their energy and the final absorption spectrum. Make sure that min(p_nbnd_occ,nbnd_occ)*min(p_nbnd_virt,nbnd_virt) is lager than the number of initial vectors ('num_init'), so you will not end up using random trial vectors which would slow down the convergence.")
    p_nbnd_virt: int = Field(10, description="Number of empty states selected from the total number of empty states computed by PWscf. This variable is useful if there are too many empty states but your are interested in only some of them. In priciple this variable and 'p_nbnd_occ' affect only the interpretation of the eigenstates, but do not effect their energy and the final absorption spectrum. Make sure that min(p_nbnd_occ,nbnd_occ)*min(p_nbnd_virt,nbnd_virt) is lager than the number of initial vectors ('num_init'), so you will not end up using random trial vectors which would slow down the convergence.")
    poor_of_ram: bool = Field(False, description="Use this variable if you do not have enough RAM (only USPP), i.e. set it to .true. When this variable is set to .false., you double the memory used for the USPP calculation, but you increase a speed of the calculation by getting rid of applying many times of s_psi and cal_bec in the calculation, which takes a lot of time (sometimes more than a half of the whole calculation) when the size of the subspace is more than 100.")
    poor_of_ram2: bool = Field(False, description="Use this variable if you do not have enough RAM (NCPP and USPP), i.e. set it to .true. When this variable is set to .false., you double the memory used for the calculation, but you increase a speed of the calculation by storing D_ and C_ basis: the calculation will be speeded up a lot when one is calculating many transitions at the same time.")
    max_iter: int = Field(100, description="Maximum number of Davidson iterations allowed. When the number of iterations arrives this number, the calculation will stop even if the convergence has not been achieved.")
    no_hxc: bool = Field(False, description="When set to .true. the change in the internal field (Hartree and exchange-correlation) is ignored in the calculation, resulting in the independent electron approximation.")
    pseudo_hermitian: bool = Field(True, description="When set to .true. the pseudo-Hermitian Lanczos algorithm is used. When set to .false. the non-Hermitian Lanczos biorthogonalization algorithm is used (which is two times slower).")
    ltammd: bool = Field(False, description="When set to .true. the Tamm-Dancoff approximation is used in constructing the Liouvillian.")
    lplot_drho: bool = Field(False, description="When set to .true. the turbo_davidson.x code will write files for each eigenstate 'drho-of-eign-$i' which are needed to plot the response charge-density at each resonance. This implies a calculation using the pp.x post-processing program with the corresponding input file which must be prepared. See example 'H2O-PLOTRHO'.")
    d0psi_rs: bool = Field(False, description="When set to .true. the dipole is computed in the real space. When set to .false. the dipole is computed in the reciprocal space by computing [H,r]. Note, currently the commutator does not contain a contribution for hybrids [V_EXX,r]. See also the variable lshift_d0psi. Important: Treatment of the dipole in the real space is allowed only if the system is finite.")
    lshift_d0psi: bool = Field(True, description="This variable is used only when d0psi_rs=.true. a) If a molecule is placed in the corner of the supercell, there is a discontinuity problem for the position operator r, which is not periodic. By setting lshift_d0psi=.true. the discontinuity problem is solved by shifting the position operator r such that it is continuous and well defined. b) If a molecule is placed in the center of the supercell, there is no discontinuity problem for the position operator r, and thus you can set lshift_d0psi=.false. But if you still set it to .true., this will not harm, because the position operator will basically remain as it is, since it is always centered wrt the center of the molecule.")


class TURBO_DAVIDSONEspressoInput(EspressoInput):
    """Pydantic model for the input of `turbo_davidson.x.`"""

    lr_input: Lr_inputNamelist = Field(default_factory=lambda: Lr_inputNamelist())
    lr_dav: Lr_davNamelist = Field(default_factory=lambda: Lr_davNamelist())
