"""Pydantic model for the input of `turbo_spectrum.x` version `qe-7.3.1-devel`.

This file has been generated automatically. Do not edit it manually.
"""

# ruff: noqa

from pathlib import Path
from pydantic import Field, field_validator
from typing import Literal
from pydantic_espresso.models.template import EspressoInput, Namelist
from pydantic_espresso.utils import get_tmp_dir, get_pseudo_dir


class Lr_inputNamelist(Namelist):
    """Pydantic model for the `Lr_input` namelist."""


    prefix: str = Field("pwscf", description="Sets the prefix for generated and read files. The files generated by the ground state pw.x run should have this same prefix.")
    outdir: Path = Field(Path("./"), description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.")
    verbosity: int = Field(1, description="This integer variable controls the amount of information written to standard output.")
    itermax0: int = Field(500, description="Number of Lanczos coefficients to be read from the file.")
    itermax: int = Field(500, description="The total number of Lanczos coefficients that will be considered in the calculation of the polarizability/absorption coefficient. If itermax > itermax0, the Lanczos coefficients in between itermax0+1 and itermax will be extrapolated.")
    extrapolation: Literal["osc", "constant", "no"] = Field("no", description="Sets the extrapolation scheme.")
    epsil: float = Field(0.02, description="The broadening/damping term. In Rydberg units if magnons=.false., in meV if magnons = .true.")
    units: int = Field(0, description="The unit system used for the output and the start, end and increment input parameters. (only meV used in that case).  0 = Rydbergs, 1 = Electron volts, 2 = Nanometres per electron volts, 3 = milli Electron volts (only for magnons=.true.)")
    start: float = Field(0.0, description="The polarizability and the absorption coefficient are computed starting from this value. In units set.")
    end: float = Field(2.5, description="The polarizability and the absorption coefficient are computed up to this value. In units set.")
    increment: float = Field(0.001, description="Incremental step used to define the mesh between start and end. In units set.")
    ipol: int = Field(1, description="An integer variable that determines which element of the dynamical polarizability will be computed: 1 -> alpha_xx(omega), 2 -> alpha_yy(omega), and 3 -> alpha_zz(omega). When set to 4, three Lanczos chains are sequentially performed and the full polarizability tensor and the absorption coefficient are computed.")
    eels: bool = Field(False, description="Must be set to .true. for EELS. EELS-specific operations will be performed.")
    magnons: bool = Field(False, description="Must be set to .true. for magnon-calculation post-processing.")
    td: str = Field("lanczos", description="When set to 'lanczos', a calculation of the spectrum is performed using the Lanczos coefficients. When set to 'davidson' or 'david', a calculation of the spectrum is performed using the eigenvalues computed using the Davidson algorithm. See the variable 'eign_file'.")
    eign_file: str = Field("pwscf.eigen", description="The name of the file produced by the turbo_davidson.x code, in which are written the eigenvalues.")


class TURBO_SPECTRUMEspressoInput(EspressoInput):
    """Pydantic model for the input of `turbo_spectrum.x.`"""

    lr_input: Lr_inputNamelist = Field(default_factory=lambda: Lr_inputNamelist())
