"""Pydantic model for the input of `turbo_eels.x` version `latest`.

This file has been generated automatically. Do not edit it manually.
"""

# ruff: noqa

from pydantic import Field
from typing import Annotated, Literal
from pydantic_espresso.models.template import EspressoInputTemplate


class TURBO_EELSEspressoInput(EspressoInputTemplate):
    """Pydantic model for the input of `turbo_eels.x.`"""

    prefix: str = Field(" 'pwscf'
         ", description="Sets the prefix for generated and read files. The files generated by the ground state pw.x run must have this same prefix.")
    outdir: str = Field(" './'
         ", description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.")
    restart: bool = Field(False, description="When set to .true., turbo_eels.x will attempt to restart from a previous interrupted calculation. (see")
    restart_step: int = Field( itermax
         , description="The code writes restart files every restart_step iterations. Restart files are automatically written at the end of itermax Lanczos steps.")
    lr_verbosity: int = Field( 1
         , description="This integer variable controls the amount of information written to standard output.")
    disk_io: str = Field(" 'default'
         ", description="Fine control of disk usage. Currently only 'reduced' is supported where no restart files are written, apart from the 'default' mode.")
    approximation: Literal["'TDDFT'", "'IPA'", "'RPA_with_CLFE'"] = Field(" 'TDDFT'
         ", description="A string describing a level of theory:")
    calculator: Literal["'lanczos'", "'sternheimer'"] = Field(" 'lanczos'
         ", description="Variable that controls which algorithm is used to compute EELS spectra.")
    itermax: int = Field( 500
         , description="When")
    pseudo_hermitian: bool = Field(True, description="This variable is used only when")
    alpha_mix(i): float = Field( alpha_mix(1)=0.7
         , description="This variable is used only when")
    epsil: float = Field( 0.02
         , description="This variable is used only when")
    units: int = Field( 0
         , description="This variable is used only when")
    start: float = Field( 0.0
         , description="This variable is used only when")
    end: float = Field( 2.5
         , description="This variable is used only when")
    increment: float = Field( 0.001
         , description="This variable is used only when")
    ethr_nscf: float = Field( 1.D-11
         , description="Threshold for the convergence of eigenvalues during the iterative diagonalization of the Hamiltonian in the non-self-consistent-field (NSCF) calculation at k and k+q points. Note, this quantity is NOT extensive.")
