"""Pydantic model for the input of `turbo_davidson.x` version `latest`.

This file has been generated automatically. Do not edit it manually.
"""

# ruff: noqa

from pydantic import Field
from typing import Annotated, Literal
from pydantic_espresso.models.template import EspressoInputTemplate


class TURBO_DAVIDSONEspressoInput(EspressoInputTemplate):
    """Pydantic model for the input of `turbo_davidson.x.`"""

    prefix: str = Field(" 'pwscf'
         ", description="Sets the prefix for generated and read files. The files generated by the ground state pw.x run should have this same prefix.")
    outdir: str = Field(" './'
         ", description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.")
    wfcdir: str = Field(" './'
         ", description="The directory that contains the run critical files, which include the files generated by ground state pw.x run.")
    max_seconds: float = Field( 1.D+7, or 150 days, i.e. no time limit
         , description="jobs stops after")
    restart: bool = Field(False, description="When set to .true., turbo_davidson.x will attempt to restart from a previous interrupted calculation if")
    lr_verbosity: int = Field( 1
         , description="This integer variable controls the amount of information written to standard output.")
    disk_io: str = Field(" 'default'
         ", description="Fine control of disk usage. Currently only 'reduced' is supported where no restart files are written, apart from the 'default' mode.")
    num_eign: int = Field( 1
         , description="Number of eigenstates to be calculated.")
    num_init: int = Field( 2
         , description="Number of trial vectors. Usually it is twice as large as the number of eigenstates to be calculated (see")
    if_random_init: bool = Field(False, description="When set to .true. trial vectors are chosen randomly, otherwise they are guessed from the ground-state calculation. If")
    num_basis_max: int = Field( 20
         , description="Maximum number of basis vectors allowed in the subspace. When this number is reached, a discharging routine is called. The memory requirement of the Davidson algorithm is mainly determined by this variable (an estimation of the memory is reported at the beginning of the run).")
    residue_conv_thr: float = Field( 1.0E-4
         , description="Threshold for the convergence. When the square of the residue is smaller than this value, the convergence is achieved.")
    precondition: bool = Field(True, description="If set to .true. a precondition is used. At this moment, one sees no reason why not to use the precondition.")
    single_pole: bool = Field(False, description="A slightly better way to set the initial trial vectors, but the improvement is really small. Currently this flag can be used only with LDA/PBE + NC PPs. So do not use it unless it is really necessary.")
    if_dft_spectrum: bool = Field(False, description="When set to .true. the independent particle approximation is used, i.e. the Hartree and exchange-correlation response contributions are neglected.")
    reference: float = Field( 0.0d0
         , description="Reference energy in units of Ry. This variable is used to constrain the Davidson algorithm to converge the eigenstates having the energy closest to the reference energy. In this way one can calculate less eigenstates at once, and to perform multiple calculations with different reference energies (the post-processing code tddfpt_calculate_spectrum.x can be used for this purpose).")
    broadening: float = Field( 0.005d0
         , description="Lorentzian broadening (Ry) to broaden the absorption spectrum.")
    start: float = Field( 0.0d0
         , description="The lower limit of the energy (Ry) scale for the spectrum calculation.")
    finish: float = Field( 1.0d0
         , description="The upper limit of the energy (Ry) scale for the spectrum calculation.")
    step: float = Field( 0.001d0
         , description="Energy step (Ry) for the spectrum calculation.")
    p_nbnd_occ: int = Field( 10
         , description="Number of occupied states selected from the total number of occupied states computed by PWscf. This variable is useful if there are too many occupied states but your are interested in only some of them. In priciple this variable and")
    p_nbnd_virt: int = Field( 10
         , description="Number of empty states selected from the total number of empty states computed by PWscf. This variable is useful if there are too many empty states but your are interested in only some of them. In priciple this variable and")
    poor_of_ram: bool = Field(False, description="Use this variable if you do not have enough RAM (only USPP), i.e. set it to .true. When this variable is set to .false., you double the memory used for the USPP calculation, but you increase a speed of the calculation by getting rid of applying many times of s_psi and cal_bec in the calculation, which takes a lot of time (sometimes more than a half of the whole calculation) when the size of the subspace is more than 100.")
    poor_of_ram2: bool = Field(False, description="Use this variable if you do not have enough RAM (NCPP and USPP), i.e. set it to .true. When this variable is set to .false., you double the memory used for the calculation, but you increase a speed of the calculation by storing D_ and C_ basis: the calculation will be speeded up a lot when one is calculating many transitions at the same time.")
    max_iter: int = Field( 100
         , description="Maximum number of Davidson iterations allowed. When the number of iterations arrives this number, the calculation will stop even if the convergence has not been achieved.")
    no_hxc: bool = Field(False, description="When set to .true. the change in the internal field (Hartree and exchange-correlation) is ignored in the calculation, resulting in the independent electron approximation.")
    pseudo_hermitian: bool = Field(True, description="When set to .true. the pseudo-Hermitian Lanczos algorithm is used. When set to .false. the non-Hermitian Lanczos biorthogonalization algorithm is used (which is two times slower).")
    ltammd: bool = Field(False, description="When set to .true. the Tamm-Dancoff approximation is used in constructing the Liouvillian.")
    lplot_drho: bool = Field(False, description="When set to .true. the turbo_davidson.x code will write files for each eigenstate 'drho-of-eign-$i' which are needed to plot the response charge-density at each resonance. This implies a calculation using the pp.x post-processing program with the corresponding input file which must be prepared. See example 'H2O-PLOTRHO'.")
    d0psi_rs: bool = Field(False, description="When set to .true. the dipole is computed in the real space. When set to .false. the dipole is computed in the reciprocal space by computing [H,r]. Note, currently the commutator does not contain a contribution for hybrids [V_EXX,r]. See also the variable")
    lshift_d0psi: bool = Field(True, description="This variable is used only when")
